name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "development", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: make
        run:
          g++ -o main main.cpp &&
          chmod +x main
      - name: check
        run: /bin/bash ./main
