name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - development
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GCC
        run: sudo apt-get install g++ -y

      - name: Build
        run: |
          g++ -o main main.cpp
          chmod +x main

      - name: Run Tests
        run: |
          ./main || exit 1
